version: "3.6"
services:

  config-server:
    image: config-server:latest
    build: ./config-server
    networks: 
      - sca-poc-network
    ports:
      - "8888:8888"

  eureka-naming-server:
    image: eureka-naming-server:latest
    build: ./eureka-naming-server
    networks: 
      - sca-poc-network
    ports:
      - "8761:8761"

  modulo-gestao-ativo:
    image: modulo-gestao-ativo:latest
    build: ./modulo-gestao-ativo
    networks: 
      - sca-poc-network
    ports:
      - "8200:8200"

  modulo-seguranca-comunicacao:
    image: modulo-seguranca-comunicacao:latest
    build: ./modulo-seguranca-comunicacao
    networks: 
      - sca-poc-network
    ports:
      - "8300:8300"

  modulo-simulacao-sensores:
    image: modulo-simulacao-sensores:latest
    build: ./modulo-simulacao-sensores
    networks: 
      - sca-poc-network
    ports:
      - "9000:9000"

  modulo-usuario:
    image: modulo-usuario:latest
    build: ./modulo-usuario
    networks:
      - sca-poc-network
    ports:
      - "8100:8100"

  active-mq:
    image: njmittet/alpine-activemq
    networks:
      - sca-poc-network
    ports:
      - 8161:8161
      - 61616:61616

networks: 
  default:
  sca-poc-network:
    ipam:
      config:
        - subnet: 20.31.0.0/16
  
