version: "3.6"
services:

  mongo:
    image: mongo:latest
    networks:
      - employee-network
    ports:
      - "27017:27017"

  config-server:
    image: config-server:latest
    build: ./config-server
    networks: 
      - employee-network
    ports:
      - "8888:8888"

  active-mq:
    image: njmittet/alpine-activemq
    networks:
      - employee-network
    ports:
      - 8161:8161
      - 61616:61616

  mongo-express:
    image: mongo-express:latest
    networks: 
      - employee-network
    ports:
      - "8081:8081"

networks: 
  default:
  employee-network:
    ipam:
      config:
        - subnet: 20.30.0.0/16
  
